### ISSUE TITLE
Ethereum Support

### ISSUE THREAD

**Issue by Lrss** [bitcartcc/bitcart#105]
Are there any plans to support Ethereum and ERC-20 tokens?

**Comment by MrNaif2018** [comment]
Hi! To add support of any coin, electrum fork for that coin should exist or be created.
But as far as I know Ethereum is different. But if there is an alternative light client (better written in python), then alternative daemon implementation can be written.
I haven't found electrum fork for ethereum. If you know one, please let me know.

**Comment by MrNaif2018** [comment]
Well, actually I found [web3py](https://web3py.readthedocs.io), but it is not using multiple servers, so not sure. BitcartCC is considered lightweight, and it works via electrum as it is SPV and uses multiple nodes. 
But web3py seems to be using only one node only. I think it doesn't fit into BitcartCC philosophy of being light but decentralized still. As a library web3py is good, but as for security and decentralization concepts - not sure.
Will continue searching, something that uses SPV would be the best.

**Comment by MrNaif2018** [comment]
Another possible option is to wait for poket network to add it's web3py provider and use it.
[This pull](https://github.com/MyEtherWallet/MyEtherWallet/pull/1262/) from myetherwallet can be used as a reference.

**Comment by MrNaif2018** [comment]
> Ok, regarding payment processing for eth, I've found 4 possible ways, 2 of them requiring hot wallet and some deployment fees (from network, not us), and the other 2 requiring only watch-only wallet, but with their own downsides
> 
> 1. Deploy a contract via factory which will do the forwarding to merchants' target address (entered in settings). Requires small gas fees to be paid for each new invoice to deploy the contract, so hot wallet is required. Also if no money was sent it still takes a fee to just deploy the new address. Theoretically though we could just re-use the expired address for a new invoice. For example BitcartCC could deploy 20 addresses (something like a gap limit in electrum), then if invoice has expired it would just take the used address again.
> 2. Use one address, also with a contract, which could help to detect payments in a reliable way. Requires to pay once to be deployed per wallet. In this case the contract would contain all the funds which could be withdrawn, or maybe it could auto-forward to the target address too. The only difference with previous method is that we will use one address for all invoices of a wallet, which might be not so good for privacy.
> 3. Use one address, but instead store order id in last digits of amount to be paid. Not sure if it is reliable enough, but there are no deployment costs
> 4. One address per invoice, as we do in btc-based chains. The problem is that, if someone pays you in USDT for example, you won't be able to withdraw from that address without sending eth to it first, also most wallets seem to work on just 1 address only, so you would manually? need to track all your addresses
> 
> If someone knows some better ways, let us know. I can't seem to find the ideal solution without downsides yet, maybe we'll have to pick from those 4

https://t.me/bitcartcc/6514

Eth support is being implemented in #268, the critical thing to choose now is how to handle the addresses thing. If you have any ideas let me know

**Comment by MrNaif2018** [comment]
@Lrss Ethereum support have been added in BitcartCC 0.6.3.0!
Please test it out!

ERC-20 tokens will be added after testing that ETH support works as expected

**Comment by Lrss** [comment]
That's amazing, great work! Will test it right away.

**Comment by MrNaif2018** [comment]
ERC20 support was added in the 0.6.4.0 release! Everyone please help testing it out!

**Comment by MrNaif2018** [comment]
Closing this issue as ETH, BNB, ERC20 and BEP20 support was added
