### ISSUE TITLE
[FEATURE] Adopt commit message guidelines

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart#118]
By adopting commit message guidelines we can get the following benefits:
- Ability to generate changelog automatically
- Ability to easily know which commit introduced which change, type of changes introduced
- And more

There are two possible guidelines we could adopt:
https://www.conventionalcommits.org/en/v1.0.0/
or
https://gitmoji.carloscuesta.me/ (used in [fastapi](https://github.com/tiangolo/fastapi), for example)

We should add notes into our contributing guidelines and decide on specific messages to use. (i.e. "BREAKING CHANGES:" vs "breaking:" vs ":boom:"

**Comment by xiaoxianma** [comment]
gitmoji looks really interesting. It provides more detailed options to users extending three main options fix/feat/breaking

**Comment by MrNaif2018** [comment]
I think that if a commit follows commit message guidelines for meaningful commits (https://chris.beams.io/posts/git-commit/), there would be no need to add additional prefixes to it. Closing
