### ISSUE TITLE
Store invoice paid currency on successful checkout

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart#120]
Currently, when invoice is paid, there is no way to check in what currency customer has paid.
A new `paid_currency` field should be added, which will be filled in in `tasks.py` on successful checkout.
This also requires an edit to [invoice page headers](https://github.com/bitcartcc/bitcart-admin/blob/master/pages/invoices.vue#L19) in admin panel to add a new field

**Comment by kartecianos** [comment]
Hi I would like to work on this

From my understanding the `paid_currency` field should be added in the `models.Invoice` class and the update of the field's value should be done in `tasks.process_invoice()` function reading the currency field of the PaymentMethod object used for processing the invoice.

**Comment by MrNaif2018** [comment]
Hi! Thank you! You are understanding right. But unfortunately this issue is already taken by @xiaoxianma. We'll comment on issues next time, sorry.
Maybe you could take a look at #121 or [bitccl](https://github.com/bitcartcc/bitccl) instead?

**Comment by kartecianos** [comment]
Ok I will check it out
