### ISSUE TITLE
Get rid of namedtuples in tor extension

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart#121]
`api/ext/tor.py` is using namedtuples.
But we have dataclasses support available in python 3.7+, and in python 3.6 via [backport](https://github.com/bitcartcc/bitcart/blob/master/requirements/base.txt#L3)
It is used in other parts of code base, only here namedtuples are used.
[HiddenService](https://github.com/bitcartcc/bitcart/blob/edc3d6ffc9c0a80ca514fb445f213a1a75767530/api/ext/tor.py#L7) and [PortDefinition](https://github.com/bitcartcc/bitcart/blob/edc3d6ffc9c0a80ca514fb445f213a1a75767530/api/ext/tor.py#L8) (and maybe [TorService](https://github.com/bitcartcc/bitcart/blob/edc3d6ffc9c0a80ca514fb445f213a1a75767530/api/ext/tor.py#L81)) need to be changed into dataclasses.

**Comment by kartecianos** [comment]
Hi, I could work on this

**Comment by MrNaif2018** [comment]
Thank you! Sure

**Comment by kartecianos** [comment]
#128

**Comment by MrNaif2018** [comment]
Fixed by #128
