### ISSUE TITLE
[FEATURE] Fix all the logos across the platform according to PR.

### ISSUE THREAD

**Issue by x-N0** [bitcartcc/bitcart#129]
All the logos (Imagotypes) across the platform should match, this can become a lil set of _"easy-fix"_ and _"low-hanging-fruits"_ for newer collaborators to help them get started with the project setup.

PR: https://github.com/bitcartcc/bitcart-media/pull/3

**Comment by x-N0** [comment]
@MrNaif2018 Fix that "bug" label.

**Comment by MrNaif2018** [comment]
To do that, use:
https://github.com/bitcartcc/bitcart-media/blob/master/logo.svg to replace logo.png in `static` folder on each website. Sizes must be the same as before.
Note: svg support must be tested separately in firefox as it had bugs with it before (at least in admin panel)

**Comment by MrNaif2018** [comment]
Done
