### ISSUE TITLE
[FEATURE] Making contributions easier 

### ISSUE THREAD

**Issue by ycd** [bitcartcc/bitcart#130]
First of all congrats @MrNaif2018 and @xiaoxianma :tada: :rocket: it is been a long time since i glanced at Bitcart, but it looks really stable and neat right now. But i have a one concern, repository having a lack of documentation, especially for contributors, setting up environment manually and a poor CONTRIBUTING.md could be frustrating for newcomers. 

But i think it can be imrpoved easily. What do you guys think about this?

**Comment by MrNaif2018** [comment]
I agree. Hacktoberfest is soon, and we will prepare everything for it. #123 is very important to get merged, afterwards we can document it all more.
Could you please tell which steps are missing?
How to set up development environment for all repos?
We have some instructions in each one, for main one, see here:
https://github.com/bitcartcc/bitcart/wiki/How-to-Contribute#setting-up-python-development-environment
For others it's in contributing.md
Maybe this link which shows how to install everything with some additions can be useful? (it shows how I setup development environment, only few commands are replaced):
https://docs.bitcartcc.com/deployment/manual

**Comment by ycd** [comment]
> We have some instructions in each one, for main one, see here:
> https://github.com/bitcartcc/bitcart/wiki/How-to-Contribute#setting-up-python-development-environment

Actually this looks enough in my case, but if i had not opened this issue i would not be seeing this documentation, most repos have them inside CONTRIBUTING.md so i firstly checked there. I think it can be moved from wiki to Contributing.

**Comment by MrNaif2018** [comment]
Well, it's there, but making too hidden? As contributing can be by not only code changes, see
https://github.com/bitcartcc/bitcart/blob/master/CONTRIBUTING.md#contributing-fixes

**Comment by MrNaif2018** [comment]
One point is that, actually, github wiki isn't included with source code, while CONTRIBUTING.md is. Is that what you mean? We might indeed move it then

**Comment by MrNaif2018** [comment]
I agree that we should move contributing guidelines to CONTRIBUTING.md. But what about our coding guidelines? They apply to all repositories. Should they also be in contributing.md and linked from other repos this way?
https://github.com/bitcartcc/bitcart/wiki/Coding-Guidelines

**Comment by ycd** [comment]
> I agree that we should move contributing guidelines to CONTRIBUTING.md. But what about our coding guidelines? They apply to all repositories. Should they also be in contributing.md and linked from other repos this way?
> https://github.com/bitcartcc/bitcart/wiki/Coding-Guidelines

Totally agree, [VS Code Python](https://github.com/Microsoft/vscode-python) keeps guidelines inside [CODING_STANDARDS.md](https://github.com/microsoft/vscode-python/blob/main/CODING_STANDARDS.md) i think that repo is a good example, we can move wiki directly to source code and the [contributing-fixes](https://github.com/bitcartcc/bitcart/blob/master/CONTRIBUTING.md#contributing-fixes) to CONTRIBUTING.md

**Comment by MrNaif2018** [comment]
Perfect! Then we can indeed move contributing part of the wiki to contributing.md, and guidelines to CODING_STANDARDS.md!
Thank you, will update the links soon and close that issue afterwards!
Other than that, anything else we should consider documenting?

**Comment by ycd** [comment]
Nope, everything else looks great, thanks again!

**Comment by MrNaif2018** [comment]
Done, see https://github.com/bitcartcc/bitcart/blob/master/CODING_STANDARDS.md and updated CONTRIBUTING.md! Thanks again!
