### ISSUE TITLE
[BUG] payment methods inconsistent order

### ISSUE THREAD

**Issue by xiaoxianma** [bitcartcc/bitcart#149]
**Describe the bug**
Sometimes, very rarely, I got payment methods displayed in the wrong order. (usually, they are ordered by the order wallets are connected to the store). Maybe it's something like a hot reload bug or something, but once I saw it in production too.

**To Reproduce**
N/A

**Comment by MrNaif2018** [comment]
It was caused by lack of id field in payment methods, should be fixed by 5ddf6347b482eaef09201ed6ea197b31edb015b6
